mysql:
  db: "information_schema"
  host: "wordpress-db-mysql.default.svc.cluster.local"
  pass: "secretpassword"
  port: 3306
  protocol: "tcp"
  user: "root"
  existingSecret: false
collectors: 
  auto_increment.columns: true
  binlog_size: true
  engine_innodb_status: true
  engine_tokudb_status: true
  global_status: true
  global_variables: true
  info_schema.clientstats: true
  info_schema.innodb_metrics: true
  info_schema.innodb_tablespaces: true
  info_schema.innodb_cmp: true
  info_schema.innodb_cmpmem: true
  info_schema.processlist: true
  info_schema.processlist.min_time: 0
  info_schema.query_response_time: true
  info_schema.tables: true
  info_schema.tables.databases: '*'
  info_schema.tablestats: true
  info_schema.userstats: true
  perf_schema.eventsstatements: true
  perf_schema.eventsstatements.digest_text_limit: 120
  perf_schema.eventsstatements.timelimit: 86400
  perf_schema.eventswaits: true
  perf_schema.file_events: true
  perf_schema.file_instances: true
  perf_schema.indexiowaits: true
  perf_schema.tableiowaits: true
  perf_schema.tablelocks: true
  perf_schema.replication_group_member_stats: true
  slave_status: true
  slave_hosts: true
  heartbeat: true
  heartbeat.database: heartbeat
  heartbeat.table: heartbeat
