apiVersion: v1
kind: Service
metadata:
  name: fe-gate
spec:
  selector:
    name: nginx
  type: NodePort
  ports:
  - name: foo # Actually, no port is needed.
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  #hostname: frontend001
  containers:
  - image: exoplatform/mysqltuner
    name: nginx-container
    command:
      - perl
      - /mysqltuner.pl
      - --host
      - edge-mariadb
      - --user
      - root
      - --pass
      - 22jIBq6szjwC7M6iMogx
      - --forcemem
      - "1000"
---
apiVersion: v1
kind: Pod
metadata:
  name: debian
  labels:
    name: debian
spec:
  containers:
  - image: debian
    name: debian-container
    command:
      - sleep
      - "3600"
